name: Development CI Pipeline

on:
  push:
    branches: [development]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build the project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test