name: Manual Production Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./web/gradlew

      - name: Build jar
        run: ./web/gradlew -p web bootJar

      - name: Run tests
        run: ./web/gradlew -p web test

      - name: List build output
        run: ls -lh web/build/libs

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Upload JAR to VPS
        run: |
          scp -i ~/.ssh/id_rsa web/build/libs/itpreminder.jar ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/deploy/

      - name: Deploy & restart service
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          set -e
          JAR_NAME=itpreminder.jar
          DEPLOY_DIR=/home/${USER}/deploy
          WEB_DIR=/home/${USER}/web
          BACKUP_DIR=/home/${USER}/backup

          echo "Creating backup folder if missing..."
          mkdir -p $BACKUP_DIR

          if [ -f $WEB_DIR/$JAR_NAME ]; then
            echo "Backing up existing jar..."
            mv $WEB_DIR/$JAR_NAME $BACKUP_DIR/${JAR_NAME}_$(date +%Y%m%d%H%M%S)
          fi

          echo "Deploying new jar..."
          mv $DEPLOY_DIR/$JAR_NAME $WEB_DIR/$JAR_NAME
          chmod +x $WEB_DIR/$JAR_NAME

          echo "Restarting service..."
          systemctl restart itpreminder.service
          echo "Deployment finished!"
          EOF
