name: Manual Production Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build jar
        run: ./gradlew build

      - name: Run tests (safety check)
        run: ./gradlew test
        
      - name: List build output
        run: ls -lh build/libs

      - name: Upload JAR to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "build/libs/itpreminder.jar"
          target: "/home/${{ secrets.VPS_USER }}/deploy/"
          overwrite: true
          strip_components: 1

      - name: Deploy & restart service
        uses: appleboy/ssh-action@v1
        env:
          JAR_NAME: "itpreminder.jar"
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Deploying new jar..."
            mv /home/${{ secrets.VPS_USER }}/deploy/$JAR_NAME /home/${{ secrets.VPS_USER }}/web/$JAR_NAME
            echo "Restarting service..."
            systemctl restart itpreminder.service
            echo "Deployment finished!"